# IMPORTANT: ANDROID_KEYSTORE_NAME has to be set on github variables

name: Release Android
description: "Setup Android for release"
inputs:
  key-properties-file:
    description: "Key properties file"
    required: true
  android-app-folder:
    description: "Android app folder"
    required: true
  project-directory:
    description: "Flutter project directory"
    required: false
    default: "mobile"
  

runs:
  using: "composite"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 15

      - name: Setup
        uses: ./.github/workflows/actions/flutter-setup
        with:
          setup-android: true
          setup-ios: false
          project-directory: ${{ inputs.project-directory }}
        env:
          ANDROID_APP_FOLDER: ${{ inputs.android-app-folder }}

      - name: Download Android Keystore
        shell: bash
        env:
          KEYSTORE_BASE_64: ${{ secrets.ANDROID_KEYSTORE_BASE_64_CONTENT }}
          KEY_PROPERTIES_BASE_64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE_64 }}
        run: |
          echo -n $KEYSTORE_BASE_64 | base64 -d > ${{ vars.ANDROID_KEYSTORE_NAME }}
          echo -n $KEY_PROPERTIES_BASE_64 | base64 -d > ${{ inputs.key-properties-file }}
        working-directory: ${{ inputs.android-app-folder }}
